name: spacetelescope_env

dependencies:
  - jupyter
  - notebook
  - pip
  - pytest
  - pytest-xdist
  - python>=3.9
  - pip:
      - asdf
      - asdf-astropy
      - asdf-standard
      - astropy
      - gwcs
      - matplotlib
      - numpy
