name: test

on: [ push ]

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          environment-file: 00_install/environment.yml
      - run: pip install nbcollection
      - run: python -m nbcollection execute .
